#!/usr/bin/env python3
from pathlib import Path
import sys
p=Path(sys.argv[1] if len(sys.argv)>1 else 'index.html')
s=p.read_text(encoding='utf-8')

s=s.replace('<h2>MPL Breakdown (ASA §4.3.3)</h2>','<h2>MPL Breakdown — Controlled §6 Screening Implementation</h2>')
s=s.replace('<tr><th>Loss Category</th><th>Method</th><th>ASA Reference</th><th style="text-align:right">Amount (AUD)</th></tr>',
            '<tr><th>Loss Category</th><th>Method</th><th>Method Reference</th><th style="text-align:right">Amount (AUD)</th></tr>')
s=s.replace('<tr><td>Cost of Casualties (MPL_CAS)</td><td>${r.CAS_total} × $6,271,750</td><td>§6.1.1</td>',
            '<tr><td>Cost of Casualties (MPL_CAS)</td><td>${r.CAS_total} × ${fmtUSD(ASA.CASUALTY_VALUE)}</td><td>§6.1.2–§6.1.3</td>')
s=s.replace('<tr><td>Environmental (MPL_ENV)</td><td>Max($237,000 bounding, asset)</td><td>§6.4</td>',
            '<tr><td>Environmental (MPL_ENV)</td><td>Controlled bounding / screened-asset evidence by phase</td><td>§6.4</td>')
s=s.replace('<tr><td>Property Damage (MPL_PD)</td><td>Max(bounding, asset)</td><td>§6.2</td>',
            '<tr><td>Property Damage (MPL_PD)</td><td>Controlled bounding / screened-asset evidence by phase</td><td>§6.2</td>')
s=s.replace('<tr><td>Loss of Use (MPL_LOU)</td><td>Max(GDP method, asset)</td><td>§6.3</td>',
            '<tr><td>Loss of Use (MPL_LOU)</td><td>Controlled GDP / screened-asset evidence by phase</td><td>§6.3</td>')

old="""  <p class="asa">
    This report is generated by the Römer MPL Platform PRE-RELEASE under the Australian Space Agency
    Maximum Probable Loss Methodology (2019). All monetary values are in Australian Dollars (AUD, 2024).
    MPL constants applied: CASUALTY_VALUE = $6,271,750; ENV_BOUNDING = $237,000;
    SECONDARY_MULT = 1.5; PROPERTY_PCT = 0.50; PROB_THRESHOLD = 1×10⁻⁷.
    Reference: ASA Flight Safety Code, Appendix D — MPL Calculation Methodology.
  </p>"""
new="""  <p class="asa">
    Controlled pre-release screening output informed by the Australian Space Agency Maximum Probable Loss Methodology,
    published 1 August 2019. Monetary values are AUD and use the controlled MPL Engine workbook values current for this run.
    Controlled constants: CASUALTY_VALUE = ${fmtUSD(ASA.CASUALTY_VALUE)}; ENV_BOUNDING = ${fmtUSD(ASA.ENV_BOUNDING)};
    SECONDARY_MULT = ${ASA.SECONDARY_MULT}; PROPERTY_PCT = ${(ASA.PROPERTY_PCT*100).toFixed(0)}%.
    The 1×10⁻⁷ probability-of-impact threshold is a methodology reference; this screening engine does not claim a supplied
    Flight Safety Code 1×10⁻⁷ impact isopleth. HVA selection remains ${escapeHTML(r.evidenceBoundary?.hvaSelection||'ROMER_SCREENING_HEURISTIC')}.
    Reference: Australian Space Agency (2019), Maximum Probable Loss Methodology, 1 August 2019.
    Independent specialist validation is required before regulatory or application use.
  </p>"""
if old in s:s=s.replace(old,new,1)
elif 'Controlled pre-release screening output informed by the Australian Space Agency Maximum Probable Loss Methodology' not in s:
    raise SystemExit('report provenance paragraph anchor not found')

for forbidden in ['$6,271,750','$237,000','Appendix D — MPL Calculation Methodology','MPL Breakdown (ASA §4.3.3)']:
    if forbidden in s:raise SystemExit('stale report provenance remains: '+forbidden)
for required in ['fmtUSD(ASA.CASUALTY_VALUE)','fmtUSD(ASA.ENV_BOUNDING)','§6.1.2–§6.1.3','Australian Space Agency (2019), Maximum Probable Loss Methodology']:
    if required not in s:raise SystemExit('report provenance missing: '+required)
p.write_text(s,encoding='utf-8')
print('generated report provenance aligned with controlled constants and 2019 methodology sections')
